//! Preview-owned GPU texture resampler using a fullscreen quad.
//!
//! The shader starts identical to `live-capture`'s resampler, but its source
//! and compiled bytecode live beside `live-selector` so preview filtering can
//! evolve without changing encoded stream pixels.

use nkcore::debug::*;
use nkcore::prelude::*;
use nkcore::*;

use windows::Win32::Graphics::{Direct3D::*, Direct3D11::*};

/// Compiled preview vertex/pixel shaders and their linear-clamp sampler.
pub struct Resampler {
    /// Procedural fullscreen-quad vertex shader.
    vs: ID3D11VertexShader,
    /// Texture sampling and opaque-output pixel shader.
    ps: ID3D11PixelShader,
    /// Linear filtering with edge clamping for scaled window content.
    sampler: ID3D11SamplerState,
}

impl Resampler {
    /// Vertex shader bytecode generated by the repository shader compiler.
    const BYTECODE_VS: &'static [u8] = include_bytes!("resample_vs_main.fxo");
    /// Pixel shader bytecode generated by the repository shader compiler.
    const BYTECODE_PS: &'static [u8] = include_bytes!("resample_ps_main.fxo");
    /// Immutable sampling policy shared by every preview frame.
    const SAMPLER_DESC: D3D11_SAMPLER_DESC = D3D11_SAMPLER_DESC {
        Filter: D3D11_FILTER_MIN_MAG_MIP_LINEAR,
        AddressU: D3D11_TEXTURE_ADDRESS_CLAMP,
        AddressV: D3D11_TEXTURE_ADDRESS_CLAMP,
        AddressW: D3D11_TEXTURE_ADDRESS_CLAMP,
        MipLODBias: 0.0,
        MaxAnisotropy: 1,
        ComparisonFunc: D3D11_COMPARISON_NEVER,
        BorderColor: [0.0, 0.0, 0.0, 0.0],
        MinLOD: 0.0,
        MaxLOD: D3D11_FLOAT32_MAX,
    };

    /// Create immutable resampling GPU state on `device`.
    ///
    /// Fails if generated bytecode is invalid for the active adapter or D3D11
    /// cannot allocate one of the immutable objects. Shader artifacts must be
    /// compiled before Rust compilation because `include_bytes!` is eager.
    pub fn new(device: &ID3D11Device) -> anyhow::Result<Self> {
        // SAFETY: `device` is valid and bytecode is generated from the local HLSL.
        let vs =
            out_var_or_err(|out| api_call!(unsafe {
                device.CreateVertexShader(
                    Self::BYTECODE_VS,
                    None,
                    Some(out))
            }))?.expect("unexpected null vertex shader");

        // SAFETY: `device` is valid and bytecode is generated from the local HLSL.
        let ps =
            out_var_or_err(|out| api_call!(unsafe {
                device.CreatePixelShader(
                    Self::BYTECODE_PS,
                    None,
                    Some(out))
            }))?.expect("unexpected null pixel shader");

        let sampler_desc = Self::SAMPLER_DESC;
        // SAFETY: `device` is valid and `sampler_desc` contains supported values.
        let sampler =
            out_var_or_err(|out| api_call!(unsafe {
                device.CreateSamplerState(
                    &raw const sampler_desc,
                    Some(out))
            }))?.expect("unexpected null sampler state");

        Ok(Self { vs, ps, sampler })
    }

    /// Draw `source_srv` into `target_rtv` using the caller's active viewport.
    ///
    /// The caller must set a valid viewport first. `ctx`, both views, and this
    /// resampler's state must belong to the same device. Resources are unbound
    /// after drawing so WGC can safely recycle its textures on the next frame.
    #[expect(clippy::multiple_unsafe_ops_per_block, reason = "one documented D3D11 state transaction")]
    pub fn resample(
        &self,
        ctx: &ID3D11DeviceContext,
        source_srv: &ID3D11ShaderResourceView,
        target_rtv: &ID3D11RenderTargetView) {
        // SAFETY: The documented same-device and viewport invariants hold. Six
        // procedural vertices form two triangles without a vertex buffer.
        unsafe {
            ctx.OMSetRenderTargets(Some(&[Some(target_rtv.clone())]), None);
            ctx.IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
            ctx.VSSetShader(Some(&self.vs), None);
            ctx.PSSetShader(Some(&self.ps), None);
            ctx.PSSetShaderResources(0, Some(&[Some(source_srv.clone())]));
            ctx.PSSetSamplers(0, Some(&[Some(self.sampler.clone())]));
            ctx.Draw(6, 0);

            ctx.OMSetRenderTargets(Some(&[]), None);
            ctx.VSSetShader(None, None);
            ctx.PSSetShader(None, None);
            ctx.PSSetShaderResources(0, Some(&[None]));
            ctx.PSSetSamplers(0, Some(&[None]));
        }
    }
}
