//! Exact-adapter asynchronous Media Foundation H.264 encoder.

#![expect(
    non_upper_case_globals,
    reason = "windows-rs projects SDK event constants with their native names")]
#![expect(
    clippy::as_pointer_underscore,
    clippy::inline_always,
    clippy::ref_as_ptr,
    reason = "generated by windows::core::implement")]

use std::{
    ptr,
    sync::mpsc::{self, Receiver, Sender},
};

use anyhow::{Context as _, ensure};
use capture_core::{AdapterLuid, VideoConfig};
use windows::{
    Win32::{
        Foundation::E_NOTIMPL,
        Graphics::Direct3D11::{ID3D11Device, ID3D11Texture2D},
        Media::MediaFoundation::*,
        System::{Com::CoTaskMemFree, Variant::VARIANT},
    },
    core::{Interface as _, Ref, implement},
};

/// Startup/shutdown guard for one Media Foundation owner thread.
pub struct MediaFoundation;

impl MediaFoundation {
    /// Start Media Foundation without socket support for the local encoder.
    pub fn start() -> anyhow::Result<Self> {
        // SAFETY: The media thread calls this once before creating MF objects.
        unsafe { MFStartup(MF_VERSION, MFSTARTUP_NOSOCKET) }
            .context("failed to start Media Foundation")?;
        Ok(Self)
    }
}

impl Drop for MediaFoundation {
    fn drop(&mut self) {
        // SAFETY: This guard exists only after a successful `MFStartup`.
        if let Err(error) = unsafe { MFShutdown() } {
            log::error!("failed to shut down Media Foundation: {error}");
        }
    }
}

/// Events in the asynchronous transform's pull protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EncoderEvent {
    /// The transform is ready to retain another input sample.
    NeedInput,
    /// The transform has at least one encoded output sample.
    HaveOutput,
    /// A drain completed; Phase 2 does not ordinarily request draining.
    DrainComplete,
    /// An informational event not used by the media loop.
    Other(MF_EVENT_TYPE),
}

/// Exact hardware encoder and its fixed media-type/device-manager state.
pub struct H264Encoder {
    transform: IMFTransform,
    event_generator: IMFMediaEventGenerator,
    codec_api: ICodecAPI,
    _device_manager: IMFDXGIDeviceManager,
}

impl H264Encoder {
    /// Enumerate on one adapter, match the exact friendly name, and start streaming.
    #[expect(clippy::multiple_unsafe_ops_per_block, reason = "ordered MF media-type transactions")]
    pub fn new(
        device: &ID3D11Device,
        adapter_luid: AdapterLuid,
        encoder_name: &str,
        config: &VideoConfig) -> anyhow::Result<Self> {
        let transform = activate_exact_encoder(adapter_luid, encoder_name)?;
        // SAFETY: The activated transform owns and returns its attributes object.
        let attributes = unsafe { transform.GetAttributes() }
            .context("failed to read encoder attributes")?;
        // SAFETY: This documented opt-in must precede async MFT operation.
        unsafe { attributes.SetUINT32(&MF_TRANSFORM_ASYNC_UNLOCK, 1) }
            .context("failed to unlock asynchronous encoder")?;

        let output_type = find_media_type(&transform, false, MFVideoFormat_H264)?;
        configure_common_video_type(&output_type, config)?;
        // SAFETY: Output type is H.264 and the fixed attributes are valid.
        unsafe {
            output_type.SetUINT32(&MF_MT_AVG_BITRATE, config.bit_rate)?;
            output_type.SetUINT32(&MF_MT_MPEG2_PROFILE, eAVEncH264VProfile_Base.0 as u32)?;
            transform.SetOutputType(0, &output_type, 0)
        }.context("failed to set fixed H.264 output type")?;

        let input_type = find_media_type(&transform, true, MFVideoFormat_NV12)?;
        configure_common_video_type(&input_type, config)?;
        // SAFETY: Input type is enumerated by this transform and fully configured.
        unsafe {
            input_type.SetUINT32(&MF_MT_INTERLACE_MODE, MFVideoInterlace_Progressive.0 as u32)?;
            transform.SetInputType(0, &input_type, 0)
        }.context("failed to set fixed NV12 input type")?;

        let mut reset_token = 0u32;
        let mut device_manager = None;
        // SAFETY: Both output pointers are initialized stack locations.
        unsafe { MFCreateDXGIDeviceManager(&raw mut reset_token, &raw mut device_manager) }
            .context("failed to create MF DXGI device manager")?;
        let device_manager = device_manager.context("MF returned a null DXGI device manager")?;
        // SAFETY: The manager and exact configured device remain alive in this encoder.
        unsafe { device_manager.ResetDevice(device, reset_token) }
            .context("failed to attach exact D3D11 device to MF manager")?;
        let manager_unknown = device_manager.cast::<windows::core::IUnknown>()?;
        // SAFETY: `ProcessMessage` documents the manager's IUnknown pointer as `usize`.
        unsafe {
            transform.ProcessMessage(
                MFT_MESSAGE_SET_D3D_MANAGER,
                manager_unknown.as_raw().addr())
        }.context("failed to set encoder D3D manager")?;

        let codec_api = transform.cast::<ICodecAPI>()
            .context("selected encoder does not expose ICodecAPI")?;
        configure_codec(&codec_api, config.frame_rate);
        let event_generator = transform.cast::<IMFMediaEventGenerator>()
            .context("selected encoder is not an asynchronous MFT")?;
        // SAFETY: Media types, D3D manager, and codec values are complete.
        unsafe {
            transform.ProcessMessage(MFT_MESSAGE_NOTIFY_BEGIN_STREAMING, 0)?;
            transform.ProcessMessage(MFT_MESSAGE_NOTIFY_START_OF_STREAM, 0)
        }.context("failed to start H.264 encoder streaming")?;
        log::info!(
            "validated exact hardware encoder '{encoder_name}' at {}x{} @ {} fps",
            config.width,
            config.height,
            config.frame_rate);
        Ok(Self {
            transform,
            event_generator,
            codec_api,
            _device_manager: device_manager,
        })
    }

    /// Block until the asynchronous transform publishes its next event.
    pub fn next_event(&self) -> anyhow::Result<EncoderEvent> {
        // SAFETY: A zero flag performs the documented synchronous wait.
        let event = unsafe { self.event_generator.GetEvent(MEDIA_EVENT_GENERATOR_GET_EVENT_FLAGS(0)) }
            .context("failed while waiting for an encoder event")?;
        // SAFETY: Both queries read immutable fields of the returned event.
        let status = unsafe { event.GetStatus() }.context("failed to read encoder event status")?;
        status.ok().context("encoder event reported a failure")?;
        // SAFETY: This query reads immutable data from the live event.
        let event_type = MF_EVENT_TYPE(
            unsafe { event.GetType() }.context("failed to read encoder event type")? as i32);
        Ok(match event_type {
            METransformNeedInput => EncoderEvent::NeedInput,
            METransformHaveOutput => EncoderEvent::HaveOutput,
            METransformDrainComplete => EncoderEvent::DrainComplete,
            event_type => EncoderEvent::Other(event_type),
        })
    }

    /// Submit one tracked GPU surface that the pool may recycle only on callback.
    #[expect(clippy::multiple_unsafe_ops_per_block, reason = "ordered tracked-sample construction")]
    pub fn submit(
        &self,
        texture: &ID3D11Texture2D,
        callback: &IMFAsyncCallback,
        timestamp_100ns: i64,
        duration_100ns: i64,
        force_keyframe: bool) -> anyhow::Result<()> {
        if force_keyframe {
            let value = VARIANT::from(1u32);
            // SAFETY: UI4 non-zero applies the request to the next ProcessInput.
            unsafe { self.codec_api.SetValue(&CODECAPI_AVEncVideoForceKeyFrame, &raw const value) }
                .context("selected encoder rejected a forced-IDR request")?;
        }

        // A tracked sample is essential: an async hardware MFT commonly retains
        // the submitted texture beyond `ProcessInput` returning.
        // SAFETY: Creation has no caller-owned pointer inputs.
        let tracked = unsafe { MFCreateTrackedSample() }
            .context("failed to create tracked encoder sample")?;
        // Register before any later fallible operation. If construction or input
        // fails after this point, dropping the sample still releases the slot.
        // SAFETY: `callback` remains owned by the release tracker for the process lifetime.
        unsafe { tracked.SetAllocator(callback, None::<&windows::core::IUnknown>) }
            .context("failed to attach NV12 release callback")?;
        let sample = tracked.cast::<IMFSample>()
            .context("tracked sample does not expose IMFSample")?;
        // SAFETY: The texture is NV12 subresource zero on the encoder's device.
        let buffer = unsafe {
            MFCreateDXGISurfaceBuffer(&ID3D11Texture2D::IID, texture, 0, false)
        }.context("failed to wrap NV12 texture in an MF buffer")?;
        // SAFETY: Sample and buffer are live; timestamps use MF's 100 ns clock.
        unsafe {
            sample.AddBuffer(&buffer)?;
            sample.SetSampleTime(timestamp_100ns)?;
            sample.SetSampleDuration(duration_100ns)?;
            self.transform.ProcessInput(0, &sample, 0)
        }.context("hardware encoder rejected a requested input sample")?;
        Ok(())
    }

    /// Borrow one encoded buffer only while its MF lock is held.
    pub fn process_output(
        &self,
        mut consume: impl FnMut(&[u8], u64) -> anyhow::Result<()>) -> anyhow::Result<()> {
        let mut output = [MFT_OUTPUT_DATA_BUFFER::default()];
        let mut status = 0u32;
        // SAFETY: The async MFT advertises provider-allocated output samples;
        // output/status point to initialized stack storage.
        unsafe { self.transform.ProcessOutput(0, &mut output, &raw mut status) }
            .context("failed to retrieve hardware encoder output")?;
        let sample = output[0].pSample.take()
            .context("encoder output event contained no sample")?;
        // Release any ancillary collection even though Phase 2 does not consume it.
        drop(output[0].pEvents.take());
        // SAFETY: The produced sample owns a timestamp assigned by the input clock.
        let timestamp_100ns = unsafe { sample.GetSampleTime() }
            .context("encoded sample has no timestamp")?;
        ensure!(timestamp_100ns >= 0, "encoded sample timestamp is negative");
        // SAFETY: The sample owns its buffers and can expose one contiguous view.
        let buffer = unsafe { sample.ConvertToContiguousBuffer() }
            .context("failed to obtain contiguous encoder output")?;
        let locked = BufferLock::new(&buffer)?;
        consume(locked.as_slice(), timestamp_100ns as u64 / 10)
    }
}

impl Drop for H264Encoder {
    fn drop(&mut self) {
        // SAFETY: Best-effort notification while the transform is still alive.
        if let Err(error) = unsafe {
            self.transform.ProcessMessage(MFT_MESSAGE_NOTIFY_END_OF_STREAM, 0)
        } {
            log::warn!("failed to end H.264 stream cleanly: {error}");
        }
    }
}

/// Callback owner and receive side used to recycle retained NV12 surfaces.
pub struct SurfaceReleaseTracker {
    callbacks: Vec<IMFAsyncCallback>,
    released: Receiver<usize>,
}

impl SurfaceReleaseTracker {
    /// Create one stable callback identity per pool slot.
    pub fn new(surface_count: usize) -> Self {
        let (sender, released) = mpsc::channel();
        let callbacks = (0..surface_count)
            .map(|slot| {
                let callback: IMFAsyncCallback = SurfaceReleaseCallback {
                    slot,
                    released: sender.clone(),
                }.into();
                callback
            })
            .collect();
        Self { callbacks, released }
    }

    /// Borrow the callback paired with a checked slot.
    pub fn callback(&self, slot: usize) -> anyhow::Result<&IMFAsyncCallback> {
        self.callbacks.get(slot).context("NV12 release callback is out of range")
    }

    /// Drain all callbacks that arrived since the media owner's last turn.
    pub fn drain(&self) -> impl Iterator<Item = usize> + '_ { self.released.try_iter() }
}

/// Minimal COM callback that transfers only a slot index to the media owner.
#[implement(IMFAsyncCallback)]
struct SurfaceReleaseCallback {
    slot: usize,
    released: Sender<usize>,
}

impl IMFAsyncCallback_Impl for SurfaceReleaseCallback_Impl {
    /// Select the Media Foundation default work queue.
    fn GetParameters(&self, _flags: *mut u32, _queue: *mut u32) -> windows::core::Result<()> {
        Err(E_NOTIMPL.into())
    }

    /// Return ownership notification without touching COM or GPU state.
    fn Invoke(&self, _result: Ref<IMFAsyncResult>) -> windows::core::Result<()> {
        // Receiver loss means the media owner is already terminating. Returning
        // success prevents shutdown from manufacturing a second diagnostic.
        let _ = self.released.send(self.slot);
        Ok(())
    }
}

/// Enumerate hardware encoders filtered to the exact adapter and friendly name.
fn activate_exact_encoder(
    adapter_luid: AdapterLuid,
    encoder_name: &str) -> anyhow::Result<IMFTransform> {
    let mut attributes = None;
    // SAFETY: The output option is initialized and one slot is sufficient.
    unsafe { MFCreateAttributes(&raw mut attributes, 1) }
        .context("failed to create encoder enumeration attributes")?;
    let attributes = attributes.context("MF returned null enumeration attributes")?;
    // MFT_ENUM_ADAPTER_LUID consumes the Win32 LUID's exact eight-byte layout.
    // SAFETY: The attribute copies the provided bytes before returning.
    unsafe { attributes.SetBlob(&MFT_ENUM_ADAPTER_LUID, &adapter_luid.get().to_le_bytes()) }
        .context("failed to restrict encoder enumeration to the configured adapter")?;
    let input = MFT_REGISTER_TYPE_INFO {
        guidMajorType: MFMediaType_Video,
        guidSubtype: MFVideoFormat_NV12,
    };
    let output = MFT_REGISTER_TYPE_INFO {
        guidMajorType: MFMediaType_Video,
        guidSubtype: MFVideoFormat_H264,
    };
    let mut raw = ptr::null_mut();
    let mut count = 0u32;
    // SAFETY: Type descriptors and output pointers remain valid through enumeration.
    unsafe {
        MFTEnum2(
            MFT_CATEGORY_VIDEO_ENCODER,
            MFT_ENUM_FLAG_HARDWARE | MFT_ENUM_FLAG_ASYNCMFT,
            Some(&raw const input),
            Some(&raw const output),
            &attributes,
            &raw mut raw,
            &raw mut count)
    }.context("failed to enumerate H.264 encoders on the configured adapter")?;
    let activations = ActivationArray { raw, count: count as usize };
    ensure!(!activations.is_empty(), "configured adapter exposes no async hardware H.264 encoder");

    let mut names = Vec::new();
    for activation in activations.iter() {
        let activation = activation.as_ref().context("encoder enumeration returned a null activation")?;
        let name = attribute_string(activation, &MFT_FRIENDLY_NAME_Attribute)?;
        names.push(name.clone());
        if name == encoder_name {
            // SAFETY: Exact-name activation comes from adapter-filtered enumeration.
            return unsafe { activation.ActivateObject::<IMFTransform>() }
                .with_context(|| format!("failed to activate exact encoder '{encoder_name}'"));
        }
    }
    anyhow::bail!(
        "encoder '{encoder_name}' is unavailable on adapter {adapter_luid}; available: {}",
        names.join(", "))
}

/// CoTaskMem-owned activation array with deterministic COM release.
struct ActivationArray {
    raw: *mut Option<IMFActivate>,
    count: usize,
}

impl ActivationArray {
    /// Whether enumeration yielded no usable array entries.
    const fn is_empty(&self) -> bool { self.raw.is_null() || self.count == 0 }

    /// Borrow the initialized array supplied by `MFTEnum2`.
    fn iter(&self) -> std::slice::Iter<'_, Option<IMFActivate>> {
        if self.raw.is_null() {
            [].iter()
        } else {
            // SAFETY: MFTEnum2 initialized `count` contiguous activation options.
            unsafe { std::slice::from_raw_parts(self.raw, self.count) }.iter()
        }
    }
}

impl Drop for ActivationArray {
    #[expect(clippy::multiple_unsafe_ops_per_block, reason = "paired COM release and array deallocation")]
    fn drop(&mut self) {
        if self.raw.is_null() {
            return;
        }
        // SAFETY: Each Option owns one enumeration reference. Taking drops the
        // references before the exact array allocation is freed with CoTaskMemFree.
        unsafe {
            for activation in std::slice::from_raw_parts_mut(self.raw, self.count) {
                drop(activation.take());
            }
            CoTaskMemFree(Some(self.raw.cast()));
        }
    }
}

/// Read one dynamically sized UTF-16 MF activation attribute.
fn attribute_string(
    attributes: &IMFAttributes,
    key: &windows::core::GUID) -> anyhow::Result<String> {
    // SAFETY: Length and value queries operate on one immutable attribute.
    let length = unsafe { attributes.GetStringLength(key) }
        .context("failed to query encoder friendly-name length")?;
    let mut buffer = vec![0u16; length as usize + 1];
    let mut written = 0u32;
    // SAFETY: The buffer includes the reported content plus null terminator.
    unsafe { attributes.GetString(key, &mut buffer, Some(&raw mut written)) }
        .context("failed to read encoder friendly name")?;
    ensure!(written <= length, "encoder friendly-name length changed during enumeration");
    Ok(String::from_utf16_lossy(&buffer[..written as usize]))
}

/// Find an exact subtype instead of depending on unstable MFT type indices.
#[expect(clippy::multiple_unsafe_ops_per_block, reason = "one branch performs exactly one MF type query")]
fn find_media_type(
    transform: &IMFTransform,
    input: bool,
    subtype: windows::core::GUID) -> anyhow::Result<IMFMediaType> {
    for index in 0..256 {
        // SAFETY: Stream zero is the single input/output stream selected at enumeration.
        let candidate = unsafe {
            if input {
                transform.GetInputAvailableType(0, index)
            } else {
                transform.GetOutputAvailableType(0, index)
            }
        };
        let candidate = match candidate {
            Ok(candidate) => candidate,
            Err(error) if error.code() == MF_E_NO_MORE_TYPES => break,
            Err(error) => return Err(error).context("failed while enumerating encoder media types"),
        };
        // SAFETY: The media type is an IMFAttributes implementation.
        let candidate_subtype = unsafe { candidate.GetGUID(&MF_MT_SUBTYPE) }
            .context("encoder media type has no subtype")?;
        if candidate_subtype == subtype {
            return Ok(candidate);
        }
    }
    anyhow::bail!("selected encoder does not expose required media subtype {subtype:?}")
}

/// Apply immutable geometry and cadence to an enumerated video media type.
#[expect(clippy::multiple_unsafe_ops_per_block, reason = "one ordered MF attribute transaction")]
fn configure_common_video_type(
    media_type: &IMFMediaType,
    config: &VideoConfig) -> anyhow::Result<()> {
    let frame_size = (u64::from(config.width) << 32) | u64::from(config.height);
    let frame_rate = (u64::from(config.frame_rate) << 32) | 1;
    // SAFETY: Packed ratios follow the documented high/low 32-bit MF layout.
    unsafe {
        media_type.SetUINT64(&MF_MT_FRAME_SIZE, frame_size)?;
        media_type.SetUINT64(&MF_MT_FRAME_RATE, frame_rate)?;
        media_type.SetUINT64(&MF_MT_PIXEL_ASPECT_RATIO, (1u64 << 32) | 1)
    }.context("failed to configure fixed encoder media type")?;
    Ok(())
}

/// Apply latency-critical codec controls while preserving useful compatibility.
fn configure_codec(codec_api: &ICodecAPI, frame_rate: u32) {
    // The already-fixed Baseline output profile is the portable no-B-frame
    // contract. Some hardware MFTs reject the redundant B-picture control.
    for (name, key, value) in [
        ("GOP size", &CODECAPI_AVEncMPVGOPSize, VARIANT::from(frame_rate.saturating_mul(2).max(1))),
        ("low-latency mode", &CODECAPI_AVLowLatencyMode, VARIANT::from(true)),
        ("CBR rate control", &CODECAPI_AVEncCommonRateControlMode,
            VARIANT::from(eAVEncCommonRateControlMode_CBR.0 as u32)),
    ] {
        // SAFETY: Each static CODECAPI key is paired with its documented VARIANT type.
        if let Err(error) = unsafe { codec_api.SetValue(key, &raw const value) } {
            log::warn!("encoder does not accept optional {name}: {error}");
        }
    }
}

/// Scoped borrow of a contiguous MF output buffer.
struct BufferLock<'a> {
    buffer: &'a IMFMediaBuffer,
    pointer: *mut u8,
    length: usize,
}

impl<'a> BufferLock<'a> {
    /// Lock a buffer and retain the exact byte extent until drop.
    fn new(buffer: &'a IMFMediaBuffer) -> anyhow::Result<Self> {
        let mut pointer = ptr::null_mut();
        let mut length = 0u32;
        // SAFETY: Outputs are initialized locals; the returned region remains
        // valid until the paired `Unlock` in `Drop`.
        unsafe { buffer.Lock(&raw mut pointer, None, Some(&raw mut length)) }
            .context("failed to lock encoded media buffer")?;
        ensure!(!pointer.is_null() || length == 0, "MF locked a null non-empty buffer");
        Ok(Self { buffer, pointer, length: length as usize })
    }

    /// Borrow the locked output without an intermediate frame allocation.
    const fn as_slice(&self) -> &[u8] {
        if self.length == 0 {
            &[]
        } else {
            // SAFETY: `new` validated the pointer and this lock remains active.
            unsafe { std::slice::from_raw_parts(self.pointer, self.length) }
        }
    }
}

impl Drop for BufferLock<'_> {
    fn drop(&mut self) {
        // SAFETY: A successful `Lock` is active exactly until this drop.
        if let Err(error) = unsafe { self.buffer.Unlock() } {
            log::error!("failed to unlock encoded media buffer: {error}");
        }
    }
}
