[package]
name = "live-selector"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
live-shared-texture = { path = "../crates/live-shared-texture" }

anyhow = { workspace = true }
clap = { workspace = true }
enumerate-windows = { workspace = true }
log = { workspace = true }
nkcore = { workspace = true, features = ["debug", "winit"] }
pretty_env_logger = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
set-dpi-awareness = { workspace = true }
toml = { workspace = true }
widestring = { workspace = true }
winrt-capture = { workspace = true }
win32-version-info = { workspace = true }
winit = { workspace = true }

windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_Com",
] }
