[package]
name = "live-capture"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
live-protocol = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
enumerate-windows = { workspace = true }
set-dpi-awareness = { workspace = true }
pretty_env_logger = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
nkcore = { workspace = true, features = ["debug"] }
pretty-name = { workspace = true }
serde_json = { workspace = true }
widestring = { workspace = true }
ureq = { workspace = true }
winrt-capture = { workspace = true }
win32-version-info = { workspace = true }

windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_System_Variant",
] }
